#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend google
   bind *:80
   mode http
   default_backend app

backend app
   balance roundrobin
   server 360811-web-01 52.91.144.193:80 check
   server 360811-web-02 54.160.72.159:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
